package org.dcsa.conformance.standards.eblsurrender.party;

public enum EblSurrenderState {
  AVAILABLE_FOR_SURRENDER,
  AMENDMENT_SURRENDER_REQUESTED,
  SURRENDERED_FOR_AMENDMENT,
  DELIVERY_SURRENDER_REQUESTED,
  SURRENDERED_FOR_DELIVERY,
}
