services:
  conformance-gateway:
    container_name: conformance-gateway
    build: .
    ports:
      - "8080:8080"

  conformance-webui:
    container_name: conformance-webui
    build: ./webui
    ports:
      - "4200:80"
    depends_on:
      - conformance-gateway
