conformance.createAutoTestingSandboxes = true
conformance.createManualTestingSandboxes = true
conformance.useDynamoDb = false
spring.threads.virtual.enabled=true
spring.web.error.include-exception=false
spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
conformance.showOnlyAllInOneSandboxes=true
#conformance.simulatedLambdaDelay=2000
