package org.dcsa.conformance.standards.tnt.v300.checks;

import java.util.Set;
import lombok.experimental.UtilityClass;

@UtilityClass
public class TntDataSets {

  static final Set<String> VALID_EVENT_CLASSIFIERS = Set.of("ACTUAL", "ESTIMATED", "PLANNED");

  static final Set<String> VALID_SHIPMENT_EVENT_TYPES =
      Set.of(
          "AMENDMENT_CANCELLED", "AMENDMENT_CONFIRMED", "AMENDMENT_DECLINED",
          "AMENDMENT_IN_PROGRESS", "AMENDMENT_RECEIVED", "APPROVED",
          "CANCELLATION_CONFIRMED", "CANCELLATION_DECLINED", "CANCELLATION_RECEIVED",
          "CANCELLED", "COMPLETED", "CONFIRMED", "DECLINED", "DRAFTED", "ISSUED",
          "ON_HOLD", "PENDING_AMENDMENT", "PENDING_APPROVAL",
          "PENDING_SURRENDER_FOR_AMENDMENT", "PENDING_SURRENDER_FOR_DELIVERY",
          "PENDING_UPDATE", "RECEIVED", "REJECTED", "RELEASED", "REQUESTED",
          "SUBMITTED", "SURRENDERED", "SURRENDERED_FOR_AMENDMENT",
          "SURRENDERED_FOR_DELIVERY", "UPDATE_CANCELLED", "UPDATE_CONFIRMED",
          "UPDATE_DECLINED", "UPDATE_IN_PROGRESS", "UPDATE_RECEIVED", "VOIDED");

  static final Set<String> VALID_DOCUMENT_REFERENCE_TYPES =
      Set.of(
          "ADVANCE_MANIFEST_FILING", "ARRIVAL_NOTICE", "BOOKING", "CARGO_SURVEY",
          "CARRIER_BOOKING_REQUEST", "CERTIFICATE_OF_ANALYSIS", "CERTIFICATE_OF_ORIGIN",
          "CONTAINER_RELEASE_ORDER", "CONTRACT_QUOTATION", "CUSTOMS_CLEARANCE",
          "DANGEROUS_GOODS_DECLARATION", "DELIVERY_INSTRUCTIONS", "DELIVERY_ORDER",
          "FUMIGATION_CERTIFICATE", "HEALTH_CERTIFICATE", "INSPECTION_CERTIFICATE",
          "INVOICE", "OUT_OF_GAUGE_DECLARATION", "PHYTOSANITARY_CERTIFICATE",
          "PROOF_OF_DELIVERY", "SHIPPING_INSTRUCTIONS", "TRANSPORT_DOCUMENT",
          "TRANSPORT_ORDER", "VERIFIED_GROSS_MASS", "VETERINARY_CERTIFICATE");

  static final Set<String> VALID_TRANSPORT_EVENT_TYPES =
      Set.of("APPROACHING", "ARRIVED", "DEPARTED");

  static final Set<String> VALID_EQUIPMENT_EVENT_TYPES =
      Set.of(
          "AVAILABLE_FOR_DROP_OFF", "AVAILABLE_FOR_PICKUP", "CROSSED", "CUSTOMS_RELEASED",
          "CUSTOMS_SELECTED_FOR_INSPECTION", "CUSTOMS_SELECTED_FOR_SCAN", "DISCHARGED",
          "DROPPED_OFF", "GATED_IN", "GATED_OUT", "INSPECTED", "LOADED", "PICKED_UP",
          "REMOVED", "RESEALED", "STRIPPED", "STUFFED");

  static final Set<String> VALID_IOT_EVENT_TYPES =
      Set.of(
          "BREADCRUMB", "DEVICE_STATUS", "DOOR_CLOSED", "DOOR_OPENED",
          "GEOFENCE_ENTRY", "GEOFENCE_EXIT", "MOTION_START", "MOTION_STOP",
          "PAIRING", "UNPAIRING");

  static final Set<String> VALID_REEFER_EVENT_TYPES = Set.of("ADJUSTED", "MEASURED");
}
